theme = "ferra"

[editor]
line-number = "relative"
mouse = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":write"
"=" = ":format"
"+" = "increment"
"minus" = "decrement"

[keys.insert]
C-c = "normal_mode"

[keys.select]
C-c = "normal_mode"