---
default_mode: locked
default_layout: default
default_shell: zsh
theme: dracula
on_force_close: quit
pane_frames: false
scrollback_editor: /usr/bin/nvim
copy_on_select: true
mouse_mode: true

themes:
  gruvbox:
    bg: '#45403d'
    fg: '#a89984'
    black: '#3c3836'
    gray: '#928374'
    red: '#cc241d'
    green: '#98971a'
    yellow: '#d79921'
    blue: '#458588'
    magenta: '#b16286'
    cyan: '#689d6a'
    white: '#ebdbb2'
    orange: '#d65d0e'
  dracula:
    fg: [248, 248, 242]
    bg: '#44475a'
    black: '#44475a'
    gray: [68, 71, 90]
    red: [255, 85, 85]
    green: [80, 250, 123]
    yellow: [241, 250, 140]
    blue: [98, 114, 164]
    magenta: [255, 121, 198]
    cyan: [139, 233, 253]
    white: [255, 255, 255]
    orange: [255, 184, 108]

plugins:
    - path: tab-bar
      tag: tab-bar
    - path: status-bar
      tag: status-bar
    - path: strider
      tag: strider
    - path: compact-bar
      tag: compact-bar

keybinds:
    unbind: true
    locked:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'a',]
    normal:
        - action: [SwitchToMode: Resize,]
          key: [Char: 'r',]
        - action: [SwitchToMode: Move,]
          key: [Char: 'm',]
        - action: [Detach,]
          key: [Char: 'd',]
        - action: [NewPane: Right, SwitchToMode: Locked,]
          key: [Char: '|',]
        - action: [NewPane: Down, SwitchToMode: Locked,]
          key: [Char: '-',]
        - action: [NewPane:, SwitchToMode: Locked,]
          key: [Char: 'n',]
        - action: [CloseFocus, SwitchToMode: Locked,]
          key: [Char: 'x',]
        - action: [NewTab: , SwitchToMode: Locked,]
          key: [Char: 'c',]
        - action: [CloseTab, SwitchToMode: Locked,]
          key: [Char: 'q',]
        - action: [ToggleFloatingPanes, SwitchToMode: Locked,]
          key: [Char: 'w']
        - action: [ToggleFocusFullscreen, SwitchToMode: Locked,]
          key: [Char: 'z',]
        - action: [SwitchToMode: RenameTab, TabNameInput: [0],]
          key: [Char: ',',]
        - action: [MoveFocus: Left, SwitchToMode: Locked,]
          key: [Char: 'h',]
        - action: [MoveFocus: Right, SwitchToMode: Locked,]
          key: [Char: 'l',]
        - action: [MoveFocus: Down, SwitchToMode: Locked,]
          key: [Char: 'j',]
        - action: [MoveFocus: Up, SwitchToMode: Locked,]
          key: [Char: 'k',]
        - action: [GoToTab: 1, SwitchToMode: Locked,]
          key: [Char: '1',]
        - action: [GoToTab: 2, SwitchToMode: Locked,]
          key: [Char: '2',]
        - action: [GoToTab: 3, SwitchToMode: Locked,]
          key: [Char: '3',]
        - action: [GoToTab: 4, SwitchToMode: Locked,]
          key: [Char: '4',]
        - action: [GoToTab: 5, SwitchToMode: Locked,]
          key: [Char: '5',]
        - action: [GoToTab: 6, SwitchToMode: Locked,]
          key: [Char: '6',]
        - action: [GoToTab: 7, SwitchToMode: Locked,]
          key: [Char: '7',]
        - action: [GoToTab: 8, SwitchToMode: Locked,]
          key: [Char: '8',]
        - action: [GoToTab: 9, SwitchToMode: Locked,]
          key: [Char: '9',]
        - action: [ToggleFocusFullscreen, SwitchToMode: Locked,]
          key: [Char: 'z',]
    renametab:
        - action: [SwitchToMode: Locked,]
          key: [Char: "\n",]
    resize:
        - action: [SwitchToMode: Locked,]
          key: [Char: "\n", Ctrl: 'c',]
        - action: [Resize: Left,]
          key: [Char: 'h', Left,]
        - action: [Resize: Down,]
          key: [Char: 'j', Down,]
        - action: [Resize: Up,]
          key: [Char: 'k', Up, ]
        - action: [Resize: Right,]
          key: [Char: 'l', Right,]
        - action: [Resize: Increase,]
          key: [Char: '+', Char: '=',]
        - action: [Resize: Decrease,]
          key: [Char: '-']
    move:
        - action: [SwitchToMode: Locked,]
          key: [Char: "\n", Ctrl: 'c',]
        - action: [MovePane: Left,]
          key: [Char: 'h', Left,]
        - action: [MovePane: Down,]
          key: [Char: 'j', Down,]
        - action: [MovePane: Up,]
          key: [Char: 'k', Up, ]
        - action: [MovePane: Right,]
          key: [Char: 'l', Right,]
